### ISSUE TITLE
Stub out async fetching of posts in Home view & Post view

### ISSUE THREAD

**Issue by JeffLowe** [meandavejustice/blog-builder#13]
### From 2.20.23 slack feedback:

Can you stub out async fetching of posts in the Home view, and async fetching of a post in the Post view - this can be a simple useMemo in each that just grabs it from the posts.js file and setStates it.  this will give me a spot to plug in the actual contract calls. in Home you will need to act like each post needs to be fetched, unless you build the fetching into BlogListItem

**Comment by cmunns** [comment]
After implementing SWR this is stale.
