### ISSUE TITLE
Change cid in posts.js to url and format

### ISSUE THREAD

**Issue by JeffLowe** [meandavejustice/blog-builder#16]
### From 2.20.23 slack feedback:

- cid in posts.js can be changed to url and formatted like  ipfs://bafybeicxpc74abbgf7khzqkc2eay7vmhgbsmo7bcymmvv4i3wqafnus2aa/sample-markdown.md  - ill be updating the contract to change cid to url as this makes the most sense. if you need code to take an ipfs:// url and gateway it with a given gateway url check the durin codebase theres a function in there that handles all edge cases.
- for gateway-ifying a ipfs:// URL you can reuse this function: https://github.com/ipfs-shipyard/Durin/blob/main/src/util/ipfs.ts#L27 (you can remove healthy and speed from the Node type)

**Comment by cmunns** [comment]
#29 implemented in this PR
